version: "3.9"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.52.0
    networks:
      - rates-api-network
    ports:
      - 9090:9090
    volumes:
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml
    depends_on:
      - homebudget-rates-api

  event-store-db:
    image: eventstore/eventstore:23.10.0-jammy
    container_name: event-store-db
    environment:
      - EVENTSTORE_INSECURE=true # let eventstore run without ceritficate
      - EVENTSTORE_EXT_TCP_PORT=1113 # set internal tcp port
      - EVENTSTORE_HTTP_PORT=2113 # set internal admin ui port
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
    ports:
      - "1113:1113" # map internal tcp port
      - "2113:2113" # map internal admin ui port
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore
    networks:
      - event-store-db-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: homebudget-elasticsearch
    ports:
      - 9250:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic-network

  filebeat:
    image: elastic/filebeat:8.11.0
    container_name: homebudget-filebeat
    ports:
      - 9350:80
    volumes:
      - ${ELK_FILEBEAT_CONFIG}:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - registry:/usr/share/filebeat/data:rw
    networks:
      - elastic-network

  homebudget-sql-server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: homebudget-sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ${SQL_VOLUME_PATH}:/var/opt/mssql/data
    networks:
      - mssql-network

  homebudget-mongo-db:
    image: mongo:7.0.5-rc0-jammy
    container_name: homebudget-mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DB_VOLUME_PATH}:/data/db
    networks:
      - mongo-network

  flyway:
    image: flyway/flyway:8.5.2
    container_name: homebudget-flyway-migration
    command: -url=jdbc:sqlserver://homebudget-sql-server -schemas=homebudget-schema -mixed=true -baselineOnMigrate=true -user=sa -password=${SQL_PASSWORD} -connectRetries=5 migrate
    volumes:
      - ${FLYWAY_SCRIPTS_PATH}:/flyway/sql
    networks:
      - mssql-network
    depends_on:
      - homebudget-sql-server

  redis_server:
    image: redis:7.0.7
    container_name: homebudget-cache
    ports:
      - "6379:6379"
    networks:
      - redis-network
    depends_on:
      - homebudget-sql-server

  kibana:
    image: kibana:8.10.4
    container_name: homebudget-kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9250
    networks:
      - elastic-network
    depends_on:
      - elasticsearch

  homebudget-rates-api:
    image: allmantool/homebudget-rates-api:${RATES_API_IMAGE_V}
    container_name: homebudget-rates-api
    build:
      context: Api\HomeBudget-Rates-Api\
      dockerfile: dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - GITHUB_RUN_ID=${GITHUB_RUN_ID}
        - PULL_REQUEST_ID=${PULL_REQUEST_ID}
        - PULL_REQUEST_SOURCE_BRANCH=${PULL_REQUEST_SOURCE_BRANCH}
        - PULL_REQUEST_TARGET_BRANCH=${PULL_REQUEST_TARGET_BRANCH}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      # - ASPNETCORE_HTTPS_PORT=5008
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5207:80"
      - "5208:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${RATES_API_JSON_PATH}:/app/appsettings.json:ro
    networks:
      - elastic-network
      - redis-network
      - mssql-network
      - rates-api-network
      - ui-network
    depends_on:
      - homebudget-ui
      - homebudget-sql-server
      - redis_server
      - elasticsearch
      - kibana
      - kafka

  homebudget-accounting-api:
    image: allmantool/homebudget-accounting-api:${ACCOUNTING_API_IMAGE_V}
    container_name: homebudget-accounting-api
    build:
      context: Api\HomeBudget-Accounting-Api\
      dockerfile: dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - GITHUB_RUN_ID=${GITHUB_RUN_ID}
        - PULL_REQUEST_ID=${PULL_REQUEST_ID}
        - PULL_REQUEST_SOURCE_BRANCH=${PULL_REQUEST_SOURCE_BRANCH}
        - PULL_REQUEST_TARGET_BRANCH=${PULL_REQUEST_TARGET_BRANCH}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      # - ASPNETCORE_HTTPS_PORT=5008
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5307:80"
      - "5308:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${ACCOUNTING_API_JSON_PATH}:/app/appsettings.json:ro
    networks:
      - elastic-network
      - redis-network
      - mssql-network
      - mongo-network
      - accounting-api-network
      - ui-network
      - kafka-net
      - event-store-db-net
    depends_on:
      - homebudget-sql-server
      - redis_server
      - elasticsearch
      - kibana
      - kafka

  homebudget-ui:
    image: allmantool/homebudget-ui:${UI_IMAGE_V}
    container_name: homebudget-ui
    build:
      context: UI\
      dockerfile: dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5407:80"
      - "5408:443"
    volumes:
      - ${UI_JSON_PATH}:/usr/share/nginx/html/config.json:ro
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf:ro
    networks:
      - elastic-network
      - accounting-api-network
      - rates-api-network
      - ui-network
      - kafka-net
      - event-store-db-net
    depends_on:
      - homebudget-sql-server
      - redis_server
      - elasticsearch
      - kibana

networks:
  accounting-api-network:
    driver: bridge
  rates-api-network:
    driver: bridge
  elastic-network:
    driver: bridge
  redis-network:
    driver: bridge
  mssql-network:
    driver: bridge
  mongo-network:
    driver: bridge
  ui-network:
    driver: bridge
  kafka-net:
    driver: bridge
  event-store-db-net:
    driver: bridge

volumes:
  elasticsearch-data:
  registry:
  eventstore-data:
  eventstore-logs:
