name: rates-api
services:
  homebudget-rates-api:
    image: allmantool/homebudget-rates-api:${RATES_API_IMAGE_V}
    container_name: homebudget-rates-api
    build:
      context: .\..\..\Api\HomeBudget-Rates-Api\
      dockerfile: dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - GITHUB_RUN_ID=${GITHUB_RUN_ID}
        - PULL_REQUEST_ID=${PULL_REQUEST_ID}
        - PULL_REQUEST_SOURCE_BRANCH=${PULL_REQUEST_SOURCE_BRANCH}
        - PULL_REQUEST_TARGET_BRANCH=${PULL_REQUEST_TARGET_BRANCH}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      # - ASPNETCORE_HTTPS_PORT=5008
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5207:80"
      - "5208:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${RATES_API_JSON_PATH}:/app/appsettings.json:ro
    networks:
      - elastic-network
      - redis-network
      - mssql-network
      - rates-api-network
      - ui-network
    depends_on:
      - homebudget-ui
      - ${SQL_SERVER}
      - redis_server
      - elasticsearch
      - kibana
