#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["HomeBudget-Web-API/HomeBudget-Web-API.csproj", "HomeBudget-Web-API/"]
COPY ["HomeBudget.DataAccess.Dapper/HomeBudget.DataAccess.Dapper.csproj", "HomeBudget.DataAccess.Dapper/"]
COPY ["HomeBudget.DataAccess/HomeBudget.DataAccess.csproj", "HomeBudget.DataAccess/"]
COPY ["HomeBudget.Core/HomeBudget.Core.csproj", "HomeBudget.Core/"]
COPY ["HomeBudget.Components.CurrencyRates/HomeBudget.Components.CurrencyRates.csproj", "HomeBudget.Components.CurrencyRates/"]
RUN dotnet restore "HomeBudget-Web-API/HomeBudget-Web-API.csproj"
COPY . .
WORKDIR "/src/HomeBudget-Web-API"
RUN dotnet build "HomeBudget-Web-API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HomeBudget-Web-API.csproj" -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HomeBudget-Web-API.dll"]