FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /scr

COPY --from=mcr.microsoft.com/dotnet/sdk:5.0 /usr/share/dotnet/shared /usr/share/dotnet/shared

COPY ["HomeBudget.Components.CurrencyRates.Tests/*.csproj", "HomeBudget.Components.CurrencyRates.Tests/"]
COPY ["HomeBudget.Components.IntegrationTests/*.csproj", "HomeBudget.Components.IntegrationTests/"]
COPY ["HomeBudget.Components.CurrencyRates/*.csproj", "HomeBudget.Components.CurrencyRates/"]
COPY ["HomeBudget.DataAccess/*.csproj", "HomeBudget.DataAccess/"]
COPY ["HomeBudget.Core/*.csproj", "HomeBudget.Core/"]
COPY ["HomeBudget-Web-API/*.csproj", "HomeBudget-Web-API/"]
COPY ["HomeBudget.DataAccess.Dapper/*.csproj", "HomeBudget.DataAccess.Dapper/"]
COPY ["docker-compose.dcproj", "."]

COPY . .

RUN dotnet restore ./HomeBudget-Web-API.sln

ARG SONAR_TOKEN
ARG PULL_REQUEST_ID
ARG PULL_REQUEST_SOURCE_BRANCH
ARG PULL_REQUEST_TARGET_BRANCH
ARG GITHUB_RUN_ID

ENV SONAR_TOKEN=${SONAR_TOKEN}
ENV PULL_REQUEST_ID=${PULL_REQUEST_ID}
ENV PULL_REQUEST_SOURCE_BRANCH=${PULL_REQUEST_SOURCE_BRANCH}
ENV PULL_REQUEST_TARGET_BRANCH=${PULL_REQUEST_TARGET_BRANCH}
ENV GITHUB_RUN_ID=${GITHUB_RUN_ID}

RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb 
RUN dpkg -i packages-microsoft-prod.deb 
RUN rm packages-microsoft-prod.deb 

RUN apt-get install -y apt-transport-https && \
    apt-get update && \
    apt-get install -y openjdk-11-jdk ant dos2unix ca-certificates-java dotnet-sdk-6.0 && \
    apt-get clean

# Fix certificate issues
RUN update-ca-certificates -f

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME
RUN export PATH=$PATH:$JAVA_HOME/bin

RUN dotnet new tool-manifest
RUN dotnet tool install dotnet-sonarscanner --tool-path /tools --version 5.6.0
RUN dotnet tool install dotnet-reportgenerator-globaltool --tool-path /tools --version 5.1.9
RUN dotnet tool install snitch --tool-path /tools --version 1.10.0

RUN dotnet tool restore

RUN echo "##vso[task.prependpath]$HOME/.dotnet/tools"
RUN export PATH="$PATH:/root/.dotnet/tools"

RUN echo '--->PULL_REQUEST_ID:' ${PULL_REQUEST_ID}
RUN echo '--->GITHUB_RUN_ID:' ${GITHUB_RUN_ID}
RUN echo '--->PULL_REQUEST_SOURCE_BRANCH:' ${PULL_REQUEST_SOURCE_BRANCH}
RUN echo '--->PULL_REQUEST_TARGET_BRANCH:' ${PULL_REQUEST_TARGET_BRANCH}

RUN dos2unix ./startsonar.sh
RUN chmod +x ./startsonar.sh
RUN ./startsonar.sh; exit 0;

RUN dotnet build HomeBudget-Web-API.sln --no-restore -c Release -o /app/build

LABEL build_version="${BUILD_VERSION}"
LABEL service=CurrencyRatesService

RUN dotnet test HomeBudget-Web-API.sln \
    --logger "trx" \
    --results-directory "/app/testresults/coverage" \
    --collect:"XPlat Code Coverage" \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=opencover \
    /p:CoverletOutput="/app/testresults/coverage/currencyRates.coverage.xml" 

RUN /tools/reportgenerator \
    -reports:'/app/testresults/coverage/**/coverage.cobertura.xml' \
    -targetdir:'/app/testresults/coverage/reports' \
    -reporttypes:'SonarQube;Cobertura'

RUN /tools/dotnet-sonarscanner end /d:sonar.login="${SONAR_TOKEN}"; exit 0;

RUN /tools/snitch

FROM build AS publish
RUN dotnet publish "HomeBudget-Web-API.sln" \
    --no-dependencies \
    --no-restore \
    --framework net7.0 \
    -c Release \
    -v Diagnostic \
    -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HomeBudget-Web-API.dll"]