name: ui
services:
  homebudget-ui:
    image: allmantool/homebudget-ui:${UI_IMAGE_V}
    container_name: homebudget-ui
    build:
      context: .\..\..\UI
      dockerfile: dockerfile
      args:
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5407:80"
      - "5408:443"
    volumes:
      - ${UI_JSON_PATH}:/usr/share/nginx/html/config.json:ro
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf:ro
    networks:
      - elastic-network
      - accounting-api-network
      - rates-api-network
      - ui-network
      - kafka-net
      - event-store-db-net
    depends_on:
      - homebudget-sql-server
      - redis_server
      - elasticsearch
      - kibana
