name: db
services:
  event-store-db:
    image: eventstore/eventstore:24.10.7-jammy
    container_name: event-store-db
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=System
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_COMMIT_TIMEOUT_MS=60000
      - EVENTSTORE_WRITE_TIMEOUT_MS=60000
      - EVENTSTORE_DISABLE_HTTP_CACHING=true
      - EVENTSTORE_MAX_MEM_TABLE_SIZE=100000
      - EVENTSTORE_CACHED_CHUNKS=512
      - EVENTSTORE_MIN_FLUSH_DELAY_MS=2000
      - EVENTSTORE_STATS_PERIOD_SEC=60
      - EVENTSTORE_SKIP_DB_VERIFY=true
    ports:
      - "1113:1113" # Map gRPC port
      - "2113:2113" # Map HTTP admin UI port
    volumes:
      - ${EVENT_DB_VOLUME_PATH}:/var/lib/eventstore
      - ${EVENT_DB_LOG_PATH}:/var/log/eventstore
    networks:
      - event-store-db-net
      - shared-monitoring-net
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "eventstore"

  kafka:
    image: confluentinc/cp-kafka:8.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "5Y7pZQq4Td6Jv4n3z2Z8Zg"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${HOME_SERVER}:9092s
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 30

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    user: "0" # Run as root temporarily to fix permissions
    networks:
      - kafka-net
      - shared-monitoring-net
    volumes:
      - ${KAFKA_STORE}/data:/var/lib/kafka/data:Z
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
      - bash
      - -c
      - |
        chown -R appuser:appuser /var/lib/kafka/data
        exec /etc/confluent/docker/run

  shared-mongo-db:
    image: mongo:7.0.24-rc0-jammy
    container_name: shared-mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DB_VOLUME_PATH}:/data/db
    networks:
      - mongo-network
      - shared-monitoring-net

  kafka-init:
    image: confluentinc/cp-kafka:8.0.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      echo 'Waiting for Kafka...';
      cub kafka-ready -b kafka:29092 1 30 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --topic accounting.accounts &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --replication-factor 1 --partitions 5 --topic accounting.payments
    networks:
      - kafka-net

  #
  #  homebudget-sql-server:
  #    image: "mcr.microsoft.com/mssql/server:2022-latest"
  #    container_name: homebudget-sql-server
  #    environment:
  #      ACCEPT_EULA: "Y"
  #      SA_PASSWORD: ${SQL_PASSWORD}
  #    ports:
  #      - "1433:1433"
  #    volumes:
  #      - ${SQL_VOLUME_PATH}:/var/opt/mssql/data
  #    networks:
  #      - mssql-network
  #

  wms-sql-server:
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    container_name: wms-sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${WMS_SQL_PASSWORD}
    ports:
      - "${SQL_SERVER_2025_PORT}:1433"
    volumes:
      - ${SQL_WMS_VOLUME_PATH}:/var/opt/mssql/data
    networks:
      - mssql-network
      - shared-monitoring-net
