name: monitoring
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.1
    networks:
      - rates-api-network
      - accounting-api-network
      - mongo-network
      - kafka-net
      - mssql-network
      - redis-network
      - ui-network
      - event-store-db-net
    ports:
      - 9090:9090
    volumes:
      - ${PROMETHEUS_CONFIG}:/etc/prometheus/prometheus.yml
    depends_on:
      - homebudget-rates-api
      - homebudget-accounting-api
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "512m"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.4.0-ubuntu
    networks:
      - rates-api-network
      - accounting-api-network
      - mongo-network
      - kafka-net
      - mssql-network
      - redis-network
      - ui-network
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_INSTALL_PLUGINS: "https://github.com/raintank/crate-datasource/archive/master.zip;crate-datasource,grafana-clock-panel,grafana-worldmap-panel,natel-plotly-panel"
    ports:
      - 3000:3000
    volumes:
      - ${GRAFANA_CONFIG}:/etc/grafana/provisioning.yml
      - ${GF_PATHS_LOGS}:/var/log/grafana
      - ${GF_STORAGE}:/var/lib/grafana
      - ${GF_PATHS_PROVISIONING}:/etc/grafana/provisioning
    depends_on:
      - prometheus
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "1g"

  mongo-db-exporter:
    image: percona/mongodb_exporter:2.37
    container_name: prometheus-mongo-db-exporter
    command:
      - "--mongodb.global-conn-pool"
      - "--collector.diagnosticdata"
      - "--discovering-mode"
      - "--compatible-mode"
      - "--mongodb.collstats-colls=admin.companies,admin.restaurnts"
      - "--collect-all"
    environment:
      - MONGODB_URI=mongodb://mongoadmin:${MONGO_DB_PASSWORD}@homebudget-mongo-db:27017/?maxPoolSize=1000&waitQueueTimeoutMS=5000
    restart: unless-stopped
    ports:
      - "9216:9216"
      - "17001:17001"
    networks:
      - mongo-network
    depends_on:
      - prometheus
      - homebudget-mongo-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "64m"

  kafka-exporter:
    image: bitnami/kafka-exporter:1.7.0
    container_name: prometheus-kafka-exporter
    command:
      - "--kafka.server=kafka:9092"
    ports:
      - 9308:9308
    networks:
      - kafka-net
    depends_on:
      - prometheus
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "64m"

  mssql-exporter:
    image: awaragi/prometheus-mssql-exporter:v1.3.0
    container_name: prometheus-mssql-exporter
    environment:
      SERVER: homebudget-sql-server
      PORT: 1433
      USERNAME: SA
      PASSWORD: ${SQL_PASSWORD}
    ports:
      - 4000:4000
    networks:
      - mssql-network
    depends_on:
      - prometheus
      - homebudget-sql-server
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "64m"

  redis-exporter:
    image: oliver006/redis_exporter:v1.67.0
    container_name: prometheus-redis-exporter
    environment:
      REDIS_ADDR: redis_server:6379
    ports:
      - 9121:9121
    networks:
      - redis-network
    depends_on:
      - prometheus
      - redis_server
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "64m"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    container_name: nginx-exporter
    command:
      - "--nginx.scrape-uri=http://localhost:5407/stub_status"
    ports:
      - 9113:9113
    networks:
      - ui-network
    depends_on:
      - prometheus
      - homebudget-ui
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "64m"

  event-store-db-exporter:
    image: marcinbudny/eventstore_exporter:0.15.4
    container_name: event-store-db-exporter
    environment:
    - EVENTSTORE_URL=http://event-store-db:2113
    - EVENTSTORE_USER=admin
    - EVENTSTORE_PASSWORD=changeit
    - ENABLE_PARKED_MESSAGES_STATS=True
    ports:
    - 9448:9448
    networks:
      - event-store-db-net
    depends_on:
      - prometheus
      - event-store-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
        window: 180s
      resources:
        limits:
          cpus: "1"
          memory: "64m"
