include:
  - Infrastructure/Deploy/docker-compose.networks.yaml
  - Infrastructure/Deploy/docker-compose.volumes.yaml
  - Infrastructure/Deploy/docker-compose.monitoring.yaml
  - Infrastructure/Deploy/docker-compose.logging.yaml
  - Db/Deploy/docker-compose.db.yaml
  - Api/Deploy/docker-compose.rates.yaml
  - Api/Deploy/docker-compose.accounting.yaml
  - UI/Deploy/docker-compose.ui.yaml

name: home-budget
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  flyway:
    image: flyway/flyway:10.17.2
    container_name: homebudget-flyway-migration
    command: >
      -mixed=true 
      -baselineOnMigrate=true
      -connectRetries=5 
      migrate
    environment:
      - FLYWAY_USER=sa
      - FLYWAY_PASSWORD=${SQL_PASSWORD}
      - FLYWAY_URL=jdbc:sqlserver://homebudget-sql-server:1433;encrypt=true;trustServerCertificate=true;
    volumes:
      - ${FLYWAY_SCRIPTS_PATH}:/flyway/sql
      - ${FLYWAY_CONFIG_PATH}:/flyway/conf
    networks:
      - mssql-network
    depends_on:
      - homebudget-sql-server

  redis_server:
    image: redis:7.0.7
    container_name: homebudget-cache
    ports:
      - "6379:6379"
    networks:
      - redis-network
    depends_on:
      - homebudget-sql-server
