include:
  - Infrastructure/docker-compose.networks.yaml
  - Infrastructure/docker-compose.volumes.yaml
  - Infrastructure/docker-compose.monitoring.yaml
  - Infrastructure/docker-compose.logging.yaml
  - Db/docker-compose.db.yaml
  - Api/docker-compose.rates.yaml
  - Api/docker-compose.accounting.yaml
  - UI/docker-compose.ui.yaml
  - Gateway/docker-compose.api.gateway.yaml

name: home-budget
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  flyway:
    image: flyway/flyway:11.8.0
    container_name: homebudget-flyway-migration
    command: >
      -mixed=true 
      -baselineOnMigrate=true
      -connectRetries=5 
      migrate
    environment:
      - FLYWAY_USER=sa
      - FLYWAY_PASSWORD=${SQL_PASSWORD}
      - FLYWAY_URL=jdbc:sqlserver://${SQL_SERVER}:${SQL_SERVER_PORT};encrypt=true;trustServerCertificate=true;
    volumes:
      - ${FLYWAY_SCRIPTS_PATH}:/flyway/sql
      - ${FLYWAY_CONFIG_PATH}:/flyway/conf
    networks:
      - mssql-network
    depends_on:
      - ${SQL_SERVER}

  redis_server:
    image: redis:8.0.0
    container_name: homebudget-cache
    ports:
      - "6379:6379"
    networks:
      - redis-network
    depends_on:
      - ${SQL_SERVER}
