name: Manage versions
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Version Bumper
        uses: michmich112/version-bumper@1.2.0
        with:
          options-file: "./.github/workflows/sem-ver-options.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
